{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "e8fc9bb0-5a90-464d-8f39-fd8be125ef45",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Date</th>\n",
       "      <th>Product</th>\n",
       "      <th>Quantity</th>\n",
       "      <th>Price</th>\n",
       "      <th>Customer_ID</th>\n",
       "      <th>Region</th>\n",
       "      <th>Total_Sales</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>01-01-2024</td>\n",
       "      <td>Phone</td>\n",
       "      <td>7.0</td>\n",
       "      <td>37300.0</td>\n",
       "      <td>CUST001</td>\n",
       "      <td>East</td>\n",
       "      <td>261100.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>02-01-2024</td>\n",
       "      <td>Headphones</td>\n",
       "      <td>4.0</td>\n",
       "      <td>15406.0</td>\n",
       "      <td>CUST002</td>\n",
       "      <td>North</td>\n",
       "      <td>61624.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>03-01-2024</td>\n",
       "      <td>Phone</td>\n",
       "      <td>2.0</td>\n",
       "      <td>21746.0</td>\n",
       "      <td>CUST003</td>\n",
       "      <td>West</td>\n",
       "      <td>43492.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>04-01-2024</td>\n",
       "      <td>Headphones</td>\n",
       "      <td>1.0</td>\n",
       "      <td>30895.0</td>\n",
       "      <td>CUST004</td>\n",
       "      <td>East</td>\n",
       "      <td>30895.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>05-01-2024</td>\n",
       "      <td>Laptop</td>\n",
       "      <td>8.0</td>\n",
       "      <td>39835.0</td>\n",
       "      <td>CUST005</td>\n",
       "      <td>North</td>\n",
       "      <td>318680.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>98</th>\n",
       "      <td>08-04-2024</td>\n",
       "      <td>Monitor</td>\n",
       "      <td>1.0</td>\n",
       "      <td>30717.0</td>\n",
       "      <td>CUST099</td>\n",
       "      <td>North</td>\n",
       "      <td>30717.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>99</th>\n",
       "      <td>09-04-2024</td>\n",
       "      <td>Headphones</td>\n",
       "      <td>5.0</td>\n",
       "      <td>23376.0</td>\n",
       "      <td>CUST100</td>\n",
       "      <td>South</td>\n",
       "      <td>116880.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>100</th>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>101</th>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>102</th>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>103 rows × 7 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "           Date     Product  Quantity    Price Customer_ID Region  Total_Sales\n",
       "0    01-01-2024       Phone       7.0  37300.0     CUST001   East     261100.0\n",
       "1    02-01-2024  Headphones       4.0  15406.0     CUST002  North      61624.0\n",
       "2    03-01-2024       Phone       2.0  21746.0     CUST003   West      43492.0\n",
       "3    04-01-2024  Headphones       1.0  30895.0     CUST004   East      30895.0\n",
       "4    05-01-2024      Laptop       8.0  39835.0     CUST005  North     318680.0\n",
       "..          ...         ...       ...      ...         ...    ...          ...\n",
       "98   08-04-2024     Monitor       1.0  30717.0     CUST099  North      30717.0\n",
       "99   09-04-2024  Headphones       5.0  23376.0     CUST100  South     116880.0\n",
       "100         NaN         NaN       NaN      NaN         NaN    NaN          NaN\n",
       "101         NaN         NaN       NaN      NaN         NaN    NaN          NaN\n",
       "102         NaN         NaN       NaN      NaN         NaN    NaN          NaN\n",
       "\n",
       "[103 rows x 7 columns]"
      ]
     },
     "execution_count": 1,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "import pandas as pd\n",
    "df = pd.read_csv('sales_data.csv')\n",
    "df"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "0206fb21-ad43-4959-822a-025476c6587b",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "(103, 7)"
      ]
     },
     "execution_count": 2,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df.shape"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "ceeb05b3-3a4f-4851-83db-427f9edaaf95",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "Index(['Date', 'Product', 'Quantity', 'Price', 'Customer_ID', 'Region',\n",
       "       'Total_Sales'],\n",
       "      dtype='object')"
      ]
     },
     "execution_count": 7,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df.columns"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "4f23988c-6f30-4cca-8c3e-16f270f06d64",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "Date            object\n",
       "Product         object\n",
       "Quantity       float64\n",
       "Price          float64\n",
       "Customer_ID     object\n",
       "Region          object\n",
       "Total_Sales    float64\n",
       "dtype: object"
      ]
     },
     "execution_count": 10,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df.dtypes"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "a91df514-be6b-4d9e-8307-8459a4d235d8",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Date</th>\n",
       "      <th>Product</th>\n",
       "      <th>Quantity</th>\n",
       "      <th>Price</th>\n",
       "      <th>Customer_ID</th>\n",
       "      <th>Region</th>\n",
       "      <th>Total_Sales</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>98</th>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>99</th>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>100</th>\n",
       "      <td>True</td>\n",
       "      <td>True</td>\n",
       "      <td>True</td>\n",
       "      <td>True</td>\n",
       "      <td>True</td>\n",
       "      <td>True</td>\n",
       "      <td>True</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>101</th>\n",
       "      <td>True</td>\n",
       "      <td>True</td>\n",
       "      <td>True</td>\n",
       "      <td>True</td>\n",
       "      <td>True</td>\n",
       "      <td>True</td>\n",
       "      <td>True</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>102</th>\n",
       "      <td>True</td>\n",
       "      <td>True</td>\n",
       "      <td>True</td>\n",
       "      <td>True</td>\n",
       "      <td>True</td>\n",
       "      <td>True</td>\n",
       "      <td>True</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>103 rows × 7 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "      Date  Product  Quantity  Price  Customer_ID  Region  Total_Sales\n",
       "0    False    False     False  False        False   False        False\n",
       "1    False    False     False  False        False   False        False\n",
       "2    False    False     False  False        False   False        False\n",
       "3    False    False     False  False        False   False        False\n",
       "4    False    False     False  False        False   False        False\n",
       "..     ...      ...       ...    ...          ...     ...          ...\n",
       "98   False    False     False  False        False   False        False\n",
       "99   False    False     False  False        False   False        False\n",
       "100   True     True      True   True         True    True         True\n",
       "101   True     True      True   True         True    True         True\n",
       "102   True     True      True   True         True    True         True\n",
       "\n",
       "[103 rows x 7 columns]"
      ]
     },
     "execution_count": 11,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df.isnull()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "id": "252d2559-c5c3-4f9c-8fa6-b00596de2b8e",
   "metadata": {},
   "outputs": [],
   "source": [
    "df.clean = df.drop_duplicates()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "id": "fed904a2-51cc-4a68-80ea-4d26d4c8fa06",
   "metadata": {},
   "outputs": [],
   "source": [
    "df_clean.to_csv(\"cleaned_data.csv\", index=False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "id": "6019184a-2ba0-4256-baed-5fcc4f84aef0",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Date</th>\n",
       "      <th>Product</th>\n",
       "      <th>Quantity</th>\n",
       "      <th>Price</th>\n",
       "      <th>Customer_ID</th>\n",
       "      <th>Region</th>\n",
       "      <th>Total_Sales</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>01-01-2024</td>\n",
       "      <td>Phone</td>\n",
       "      <td>7.0</td>\n",
       "      <td>37300.0</td>\n",
       "      <td>CUST001</td>\n",
       "      <td>East</td>\n",
       "      <td>261100.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>02-01-2024</td>\n",
       "      <td>Headphones</td>\n",
       "      <td>4.0</td>\n",
       "      <td>15406.0</td>\n",
       "      <td>CUST002</td>\n",
       "      <td>North</td>\n",
       "      <td>61624.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>03-01-2024</td>\n",
       "      <td>Phone</td>\n",
       "      <td>2.0</td>\n",
       "      <td>21746.0</td>\n",
       "      <td>CUST003</td>\n",
       "      <td>West</td>\n",
       "      <td>43492.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>04-01-2024</td>\n",
       "      <td>Headphones</td>\n",
       "      <td>1.0</td>\n",
       "      <td>30895.0</td>\n",
       "      <td>CUST004</td>\n",
       "      <td>East</td>\n",
       "      <td>30895.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>05-01-2024</td>\n",
       "      <td>Laptop</td>\n",
       "      <td>8.0</td>\n",
       "      <td>39835.0</td>\n",
       "      <td>CUST005</td>\n",
       "      <td>North</td>\n",
       "      <td>318680.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>98</th>\n",
       "      <td>08-04-2024</td>\n",
       "      <td>Monitor</td>\n",
       "      <td>1.0</td>\n",
       "      <td>30717.0</td>\n",
       "      <td>CUST099</td>\n",
       "      <td>North</td>\n",
       "      <td>30717.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>99</th>\n",
       "      <td>09-04-2024</td>\n",
       "      <td>Headphones</td>\n",
       "      <td>5.0</td>\n",
       "      <td>23376.0</td>\n",
       "      <td>CUST100</td>\n",
       "      <td>South</td>\n",
       "      <td>116880.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>100</th>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>101</th>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>102</th>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>103 rows × 7 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "           Date     Product  Quantity    Price Customer_ID Region  Total_Sales\n",
       "0    01-01-2024       Phone       7.0  37300.0     CUST001   East     261100.0\n",
       "1    02-01-2024  Headphones       4.0  15406.0     CUST002  North      61624.0\n",
       "2    03-01-2024       Phone       2.0  21746.0     CUST003   West      43492.0\n",
       "3    04-01-2024  Headphones       1.0  30895.0     CUST004   East      30895.0\n",
       "4    05-01-2024      Laptop       8.0  39835.0     CUST005  North     318680.0\n",
       "..          ...         ...       ...      ...         ...    ...          ...\n",
       "98   08-04-2024     Monitor       1.0  30717.0     CUST099  North      30717.0\n",
       "99   09-04-2024  Headphones       5.0  23376.0     CUST100  South     116880.0\n",
       "100         NaN         NaN       NaN      NaN         NaN    NaN          NaN\n",
       "101         NaN         NaN       NaN      NaN         NaN    NaN          NaN\n",
       "102         NaN         NaN       NaN      NaN         NaN    NaN          NaN\n",
       "\n",
       "[103 rows x 7 columns]"
      ]
     },
     "execution_count": 19,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "8a075f21-2851-4182-9f72-3d3b5da5bed4",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Best Product: Laptop\n",
      "Revenue Generated: 3889210.0\n",
      "Total Revenue: ₹12,365,048.00\n"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "df= pd.read_csv('sales_data.csv')\n",
    "total_revenue = df[\"Total_Sales\"].sum()\n",
    "product_sales = df.groupby(\"Product\")[\"Total_Sales\"].sum()\n",
    "# Find best product\n",
    "best_product = product_sales.idxmax()\n",
    "best_product_revenue = product_sales.max()\n",
    "# Display result\n",
    "print(\"Best Product:\", best_product)\n",
    "print(\"Revenue Generated:\", round(best_product_revenue, 2))\n",
    "print(f'Total Revenue: ₹{total_revenue:,.2f}')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "id": "59723916-ace4-43c6-8325-5b5c145ac066",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Total Revenue: ₹12,365,048.00 Strong overall sales performance observed\n",
      "Best Product: Laptop Strong overall sales performance observed\n",
      "Revenue Generated: 3889210.0 High customer demand for this product\n",
      "Top Region North This region generates the highest sales\n",
      "Top Region Revenue 3983635.0 Strong regional market presence\n",
      "Unique Customers 100 Sales are spread across a diverse customer base\n",
      "Total Quantity Sold 478 Indicates consistent purchasing activity\n"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "df= pd.read_csv('sales_data.csv')\n",
    "total_revenue = df[\"Total_Sales\"].sum()\n",
    "product_sales = df.groupby(\"Product\")[\"Total_Sales\"].sum()\n",
    "#top region\n",
    "top_region = df.groupby(\"Region\")[\"Total_Sales\"].sum().idxmax()\n",
    "top_region_revenue = df.groupby(\"Region\")[\"Total_Sales\"].sum().max()\n",
    "\n",
    "unique_customers = df[\"Customer_ID\"].nunique()\n",
    "\n",
    "# Find best product\n",
    "best_product = product_sales.idxmax()\n",
    "best_product_revenue = product_sales.max()\n",
    "\n",
    "# Display result\n",
    "print(f'Total Revenue: ₹{total_revenue:,.2f} Strong overall sales performance observed')\n",
    "print(\"Best Product:\", best_product ,\"Strong overall sales performance observed\")\n",
    "print(\"Revenue Generated:\", round(best_product_revenue, 2),\"High customer demand for this product\")\n",
    "print(\"Top Region\", top_region, \"This region generates the highest sales\")\n",
    "print(\"Top Region Revenue\", round(top_region_revenue, 2),\"Strong regional market presence\")\n",
    "print(\"Unique Customers\", unique_customers, \"Sales are spread across a diverse customer base\")\n",
    "print(\"Total Quantity Sold\", int(total_quantity), \"Indicates consistent purchasing activity\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "02ed7301-5de2-4c4d-a60d-c341701a5986",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
